server: 
  host: "localhost"
  port: 8080

cloudPlugins:
  - name: "example"
    host: "localhost"
    port: 1002
  # - name: "gcp"
  #   host: "localhost"
  #   port: 1000
  # - name: "azure"
  #   host: "localhost"
  #   port: 1001