server: 
  host: "localhost"
  port: 8080
  rpcPort: 8081

cloudPlugins:
  - name: "example"
    host: "localhost"
    port: 1002
    invDeployment: ""
  # - name: "gcp"
  #   host: "localhost"
  #   port: 1000
  # - name: "azure"
  #   host: "localhost"
  #   port: 1001

tagService:
  host: "localhost"
  port: 6000
